version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: air-quality-api
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
      - IQAIR_API_KEY=${IQAIR_API_KEY}
    depends_on:
      mongodb:
        condition: service_healthy
    command: sh -c "sleep 5 && npm run dev:server"
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: air-quality-worker
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017/air-quality?authSource=admin
      - IQAIR_API_KEY=${IQAIR_API_KEY}
    depends_on:
      mongodb:
        condition: service_healthy
    command: sh -c "sleep 10 && npm run dev:worker"
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: air-quality-mongodb
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: air-quality
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: mongosh --eval 'db.runCommand("ping").ok' --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    restart: unless-stopped

volumes:
  mongodb_data:
    name: air-quality-data 